// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9YriKSSTbpbxo3-mlEOAEs-cx94Dtmeg',
    appId: '1:269058947657:android:5cb1996b0256d700cb9d98',
    messagingSenderId: '269058947657',
    projectId: 'parking-d4961',
    databaseURL: 'https://parking-d4961-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'parking-d4961.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWEEJ8HXlC1amjfCxk_MVhGInoq4q7JP8',
    appId: '1:269058947657:ios:882ab8efff2c264bcb9d98',
    messagingSenderId: '269058947657',
    projectId: 'parking-d4961',
    databaseURL: 'https://parking-d4961-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'parking-d4961.appspot.com',
    iosClientId: '269058947657-r9lrsvuf1uoa23d11k7i5obmspnm8jag.apps.googleusercontent.com',
    iosBundleId: 'com.example.f',
  );
}
